name: Croma Discount Tracker

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  track-deals:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
           - name: Run Croma Tracker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python -u croma_tracker.py
